// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: compendiumLogic.proto

package compendium

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogicService_InboxMessage_FullMethodName       = "/compendiumLogic.LogicService/InboxMessage"
	LogicService_CorpMembersApiRead_FullMethodName = "/compendiumLogic.LogicService/CorpMembersApiRead"
	LogicService_ApiGetUserAlts_FullMethodName     = "/compendiumLogic.LogicService/apiGetUserAlts"
)

// LogicServiceClient is the client API for LogicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Определение сервиса и функции LogicRs
type LogicServiceClient interface {
	InboxMessage(ctx context.Context, in *IncomingMessage, opts ...grpc.CallOption) (*Empty, error)
	CorpMembersApiRead(ctx context.Context, in *ReqCorpMembersApiRead, opts ...grpc.CallOption) (*ResCorpMembersApiRead, error)
	ApiGetUserAlts(ctx context.Context, in *ReqApiGetUserAlts, opts ...grpc.CallOption) (*ResApiGetUserAlts, error)
}

type logicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicServiceClient(cc grpc.ClientConnInterface) LogicServiceClient {
	return &logicServiceClient{cc}
}

func (c *logicServiceClient) InboxMessage(ctx context.Context, in *IncomingMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LogicService_InboxMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) CorpMembersApiRead(ctx context.Context, in *ReqCorpMembersApiRead, opts ...grpc.CallOption) (*ResCorpMembersApiRead, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResCorpMembersApiRead)
	err := c.cc.Invoke(ctx, LogicService_CorpMembersApiRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) ApiGetUserAlts(ctx context.Context, in *ReqApiGetUserAlts, opts ...grpc.CallOption) (*ResApiGetUserAlts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResApiGetUserAlts)
	err := c.cc.Invoke(ctx, LogicService_ApiGetUserAlts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicServiceServer is the server API for LogicService service.
// All implementations must embed UnimplementedLogicServiceServer
// for forward compatibility.
//
// Определение сервиса и функции LogicRs
type LogicServiceServer interface {
	InboxMessage(context.Context, *IncomingMessage) (*Empty, error)
	CorpMembersApiRead(context.Context, *ReqCorpMembersApiRead) (*ResCorpMembersApiRead, error)
	ApiGetUserAlts(context.Context, *ReqApiGetUserAlts) (*ResApiGetUserAlts, error)
	mustEmbedUnimplementedLogicServiceServer()
}

// UnimplementedLogicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogicServiceServer struct{}

func (UnimplementedLogicServiceServer) InboxMessage(context.Context, *IncomingMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InboxMessage not implemented")
}
func (UnimplementedLogicServiceServer) CorpMembersApiRead(context.Context, *ReqCorpMembersApiRead) (*ResCorpMembersApiRead, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CorpMembersApiRead not implemented")
}
func (UnimplementedLogicServiceServer) ApiGetUserAlts(context.Context, *ReqApiGetUserAlts) (*ResApiGetUserAlts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiGetUserAlts not implemented")
}
func (UnimplementedLogicServiceServer) mustEmbedUnimplementedLogicServiceServer() {}
func (UnimplementedLogicServiceServer) testEmbeddedByValue()                      {}

// UnsafeLogicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogicServiceServer will
// result in compilation errors.
type UnsafeLogicServiceServer interface {
	mustEmbedUnimplementedLogicServiceServer()
}

func RegisterLogicServiceServer(s grpc.ServiceRegistrar, srv LogicServiceServer) {
	// If the following call pancis, it indicates UnimplementedLogicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogicService_ServiceDesc, srv)
}

func _LogicService_InboxMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).InboxMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_InboxMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).InboxMessage(ctx, req.(*IncomingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_CorpMembersApiRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCorpMembersApiRead)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).CorpMembersApiRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_CorpMembersApiRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).CorpMembersApiRead(ctx, req.(*ReqCorpMembersApiRead))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_ApiGetUserAlts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqApiGetUserAlts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).ApiGetUserAlts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_ApiGetUserAlts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).ApiGetUserAlts(ctx, req.(*ReqApiGetUserAlts))
	}
	return interceptor(ctx, in, info, handler)
}

// LogicService_ServiceDesc is the grpc.ServiceDesc for LogicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compendiumLogic.LogicService",
	HandlerType: (*LogicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InboxMessage",
			Handler:    _LogicService_InboxMessage_Handler,
		},
		{
			MethodName: "CorpMembersApiRead",
			Handler:    _LogicService_CorpMembersApiRead_Handler,
		},
		{
			MethodName: "apiGetUserAlts",
			Handler:    _LogicService_ApiGetUserAlts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compendiumLogic.proto",
}
