// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.0--rc2
// source: rs2.proto

package rs_bot2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Other struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsersIds      []string               `protobuf:"bytes,1,rep,name=UsersIds,proto3" json:"UsersIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Other) Reset() {
	*x = Other{}
	mi := &file_rs2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Other) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Other) ProtoMessage() {}

func (x *Other) ProtoReflect() protoreflect.Message {
	mi := &file_rs2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Other.ProtoReflect.Descriptor instead.
func (*Other) Descriptor() ([]byte, []int) {
	return file_rs2_proto_rawDescGZIP(), []int{0}
}

func (x *Other) GetUsersIds() []string {
	if x != nil {
		return x.UsersIds
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rs2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rs2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rs2_proto_rawDescGZIP(), []int{1}
}

type InMessageV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
	Tip           string                 `protobuf:"bytes,2,opt,name=Tip,proto3" json:"Tip,omitempty"`
	NameNick      string                 `protobuf:"bytes,3,opt,name=NameNick,proto3" json:"NameNick,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	NameMention   string                 `protobuf:"bytes,6,opt,name=NameMention,proto3" json:"NameMention,omitempty"`
	Messenger     map[string]string      `protobuf:"bytes,7,rep,name=Messenger,proto3" json:"Messenger,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Config        *CorporationConfig     `protobuf:"bytes,8,opt,name=Config,proto3" json:"Config,omitempty"`
	Options       []string               `protobuf:"bytes,9,rep,name=Options,proto3" json:"Options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InMessageV2) Reset() {
	*x = InMessageV2{}
	mi := &file_rs2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InMessageV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InMessageV2) ProtoMessage() {}

func (x *InMessageV2) ProtoReflect() protoreflect.Message {
	mi := &file_rs2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InMessageV2.ProtoReflect.Descriptor instead.
func (*InMessageV2) Descriptor() ([]byte, []int) {
	return file_rs2_proto_rawDescGZIP(), []int{2}
}

func (x *InMessageV2) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InMessageV2) GetTip() string {
	if x != nil {
		return x.Tip
	}
	return ""
}

func (x *InMessageV2) GetNameNick() string {
	if x != nil {
		return x.NameNick
	}
	return ""
}

func (x *InMessageV2) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *InMessageV2) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InMessageV2) GetNameMention() string {
	if x != nil {
		return x.NameMention
	}
	return ""
}

func (x *InMessageV2) GetMessenger() map[string]string {
	if x != nil {
		return x.Messenger
	}
	return nil
}

func (x *InMessageV2) GetConfig() *CorporationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InMessageV2) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CorporationConfig struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Uid           string                      `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Channels      map[string]*ChannelInfo     `protobuf:"bytes,2,rep,name=Channels,proto3" json:"Channels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bonuses       []*GameSettings             `protobuf:"bytes,3,rep,name=Bonuses,proto3" json:"Bonuses,omitempty"`
	HelpMessage   map[string]*HelpMessageInfo `protobuf:"bytes,4,rep,name=HelpMessage,proto3" json:"HelpMessage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorporationConfig) Reset() {
	*x = CorporationConfig{}
	mi := &file_rs2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorporationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorporationConfig) ProtoMessage() {}

func (x *CorporationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rs2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorporationConfig.ProtoReflect.Descriptor instead.
func (*CorporationConfig) Descriptor() ([]byte, []int) {
	return file_rs2_proto_rawDescGZIP(), []int{3}
}

func (x *CorporationConfig) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CorporationConfig) GetChannels() map[string]*ChannelInfo {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *CorporationConfig) GetBonuses() []*GameSettings {
	if x != nil {
		return x.Bonuses
	}
	return nil
}

func (x *CorporationConfig) GetHelpMessage() map[string]*HelpMessageInfo {
	if x != nil {
		return x.HelpMessage
	}
	return nil
}

type ChannelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	mi := &file_rs2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rs2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_rs2_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelInfo) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type HelpMessageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelpMessageInfo) Reset() {
	*x = HelpMessageInfo{}
	mi := &file_rs2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelpMessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelpMessageInfo) ProtoMessage() {}

func (x *HelpMessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rs2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelpMessageInfo.ProtoReflect.Descriptor instead.
func (*HelpMessageInfo) Descriptor() ([]byte, []int) {
	return file_rs2_proto_rawDescGZIP(), []int{5}
}

func (x *HelpMessageInfo) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type GameSettings struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GameCorporation   string                 `protobuf:"bytes,1,opt,name=GameCorporation,proto3" json:"GameCorporation,omitempty"`
	GameCorporationId string                 `protobuf:"bytes,2,opt,name=GameCorporationId,proto3" json:"GameCorporationId,omitempty"`
	Alias             string                 `protobuf:"bytes,3,opt,name=Alias,proto3" json:"Alias,omitempty"`
	GameLevel         int32                  `protobuf:"varint,4,opt,name=GameLevel,proto3" json:"GameLevel,omitempty"`
	GameXP            int32                  `protobuf:"varint,5,opt,name=GameXP,proto3" json:"GameXP,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameSettings) Reset() {
	*x = GameSettings{}
	mi := &file_rs2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSettings) ProtoMessage() {}

func (x *GameSettings) ProtoReflect() protoreflect.Message {
	mi := &file_rs2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSettings.ProtoReflect.Descriptor instead.
func (*GameSettings) Descriptor() ([]byte, []int) {
	return file_rs2_proto_rawDescGZIP(), []int{6}
}

func (x *GameSettings) GetGameCorporation() string {
	if x != nil {
		return x.GameCorporation
	}
	return ""
}

func (x *GameSettings) GetGameCorporationId() string {
	if x != nil {
		return x.GameCorporationId
	}
	return ""
}

func (x *GameSettings) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *GameSettings) GetGameLevel() int32 {
	if x != nil {
		return x.GameLevel
	}
	return 0
}

func (x *GameSettings) GetGameXP() int32 {
	if x != nil {
		return x.GameXP
	}
	return 0
}

var File_rs2_proto protoreflect.FileDescriptor

const file_rs2_proto_rawDesc = "" +
	"\n" +
	"\trs2.proto\x12\x03rs2\"#\n" +
	"\x05other\x12\x1a\n" +
	"\bUsersIds\x18\x01 \x03(\tR\bUsersIds\"\a\n" +
	"\x05Empty\"\xec\x02\n" +
	"\vInMessageV2\x12\x12\n" +
	"\x04Text\x18\x01 \x01(\tR\x04Text\x12\x10\n" +
	"\x03Tip\x18\x02 \x01(\tR\x03Tip\x12\x1a\n" +
	"\bNameNick\x18\x03 \x01(\tR\bNameNick\x12\x1a\n" +
	"\bUserName\x18\x04 \x01(\tR\bUserName\x12\x16\n" +
	"\x06UserId\x18\x05 \x01(\tR\x06UserId\x12 \n" +
	"\vNameMention\x18\x06 \x01(\tR\vNameMention\x12=\n" +
	"\tMessenger\x18\a \x03(\v2\x1f.rs2.InMessageV2.MessengerEntryR\tMessenger\x12.\n" +
	"\x06Config\x18\b \x01(\v2\x16.rs2.CorporationConfigR\x06Config\x12\x18\n" +
	"\aOptions\x18\t \x03(\tR\aOptions\x1a<\n" +
	"\x0eMessengerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x03\n" +
	"\x11CorporationConfig\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\tR\x03Uid\x12@\n" +
	"\bChannels\x18\x02 \x03(\v2$.rs2.CorporationConfig.ChannelsEntryR\bChannels\x12+\n" +
	"\aBonuses\x18\x03 \x03(\v2\x11.rs2.GameSettingsR\aBonuses\x12I\n" +
	"\vHelpMessage\x18\x04 \x03(\v2'.rs2.CorporationConfig.HelpMessageEntryR\vHelpMessage\x1aM\n" +
	"\rChannelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.rs2.ChannelInfoR\x05value:\x028\x01\x1aT\n" +
	"\x10HelpMessageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.rs2.HelpMessageInfoR\x05value:\x028\x01\"v\n" +
	"\vChannelInfo\x12.\n" +
	"\x04Data\x18\x01 \x03(\v2\x1a.rs2.ChannelInfo.DataEntryR\x04Data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\x0fHelpMessageInfo\x122\n" +
	"\x04Data\x18\x01 \x03(\v2\x1e.rs2.HelpMessageInfo.DataEntryR\x04Data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\fGameSettings\x12(\n" +
	"\x0fGameCorporation\x18\x01 \x01(\tR\x0fGameCorporation\x12,\n" +
	"\x11GameCorporationId\x18\x02 \x01(\tR\x11GameCorporationId\x12\x14\n" +
	"\x05Alias\x18\x03 \x01(\tR\x05Alias\x12\x1c\n" +
	"\tGameLevel\x18\x04 \x01(\x05R\tGameLevel\x12\x16\n" +
	"\x06GameXP\x18\x05 \x01(\x05R\x06GameXP2^\n" +
	"\fLogicService\x12(\n" +
	"\bLogicRs2\x12\x10.rs2.InMessageV2\x1a\n" +
	".rs2.Empty\x12$\n" +
	"\n" +
	"OtherQueue\x12\n" +
	".rs2.other\x1a\n" +
	".rs2.EmptyB/Z-github.com/mentalisit/restapi/rs_bot2;rs_bot2b\x06proto3"

var (
	file_rs2_proto_rawDescOnce sync.Once
	file_rs2_proto_rawDescData []byte
)

func file_rs2_proto_rawDescGZIP() []byte {
	file_rs2_proto_rawDescOnce.Do(func() {
		file_rs2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rs2_proto_rawDesc), len(file_rs2_proto_rawDesc)))
	})
	return file_rs2_proto_rawDescData
}

var file_rs2_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rs2_proto_goTypes = []any{
	(*Other)(nil),             // 0: rs2.other
	(*Empty)(nil),             // 1: rs2.Empty
	(*InMessageV2)(nil),       // 2: rs2.InMessageV2
	(*CorporationConfig)(nil), // 3: rs2.CorporationConfig
	(*ChannelInfo)(nil),       // 4: rs2.ChannelInfo
	(*HelpMessageInfo)(nil),   // 5: rs2.HelpMessageInfo
	(*GameSettings)(nil),      // 6: rs2.GameSettings
	nil,                       // 7: rs2.InMessageV2.MessengerEntry
	nil,                       // 8: rs2.CorporationConfig.ChannelsEntry
	nil,                       // 9: rs2.CorporationConfig.HelpMessageEntry
	nil,                       // 10: rs2.ChannelInfo.DataEntry
	nil,                       // 11: rs2.HelpMessageInfo.DataEntry
}
var file_rs2_proto_depIdxs = []int32{
	7,  // 0: rs2.InMessageV2.Messenger:type_name -> rs2.InMessageV2.MessengerEntry
	3,  // 1: rs2.InMessageV2.Config:type_name -> rs2.CorporationConfig
	8,  // 2: rs2.CorporationConfig.Channels:type_name -> rs2.CorporationConfig.ChannelsEntry
	6,  // 3: rs2.CorporationConfig.Bonuses:type_name -> rs2.GameSettings
	9,  // 4: rs2.CorporationConfig.HelpMessage:type_name -> rs2.CorporationConfig.HelpMessageEntry
	10, // 5: rs2.ChannelInfo.Data:type_name -> rs2.ChannelInfo.DataEntry
	11, // 6: rs2.HelpMessageInfo.Data:type_name -> rs2.HelpMessageInfo.DataEntry
	4,  // 7: rs2.CorporationConfig.ChannelsEntry.value:type_name -> rs2.ChannelInfo
	5,  // 8: rs2.CorporationConfig.HelpMessageEntry.value:type_name -> rs2.HelpMessageInfo
	2,  // 9: rs2.LogicService.LogicRs2:input_type -> rs2.InMessageV2
	0,  // 10: rs2.LogicService.OtherQueue:input_type -> rs2.other
	1,  // 11: rs2.LogicService.LogicRs2:output_type -> rs2.Empty
	1,  // 12: rs2.LogicService.OtherQueue:output_type -> rs2.Empty
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rs2_proto_init() }
func file_rs2_proto_init() {
	if File_rs2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rs2_proto_rawDesc), len(file_rs2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rs2_proto_goTypes,
		DependencyIndexes: file_rs2_proto_depIdxs,
		MessageInfos:      file_rs2_proto_msgTypes,
	}.Build()
	File_rs2_proto = out.File
	file_rs2_proto_goTypes = nil
	file_rs2_proto_depIdxs = nil
}
