// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.0--rc2
// source: bridge2.proto

package bridge2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для FileInfo
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	FileId        string                 `protobuf:"bytes,5,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_bridge2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bridge2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_bridge2_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// Сообщение для BridgeMessageReply
type BridgeMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeMessage   int64                  `protobuf:"varint,1,opt,name=time_message,json=timeMessage,proto3" json:"time_message,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeMessageReply) Reset() {
	*x = BridgeMessageReply{}
	mi := &file_bridge2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeMessageReply) ProtoMessage() {}

func (x *BridgeMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_bridge2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeMessageReply.ProtoReflect.Descriptor instead.
func (*BridgeMessageReply) Descriptor() ([]byte, []int) {
	return file_bridge2_proto_rawDescGZIP(), []int{1}
}

func (x *BridgeMessageReply) GetTimeMessage() int64 {
	if x != nil {
		return x.TimeMessage
	}
	return 0
}

func (x *BridgeMessageReply) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *BridgeMessageReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *BridgeMessageReply) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// Основное сообщение для передачи данных в мост
type ToBridgeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Tip           string                 `protobuf:"bytes,4,opt,name=tip,proto3" json:"tip,omitempty"`
	ChatId        string                 `protobuf:"bytes,5,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MesId         string                 `protobuf:"bytes,6,opt,name=mes_id,json=mesId,proto3" json:"mes_id,omitempty"`
	GuildId       string                 `protobuf:"bytes,7,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	TimeMessage   int64                  `protobuf:"varint,8,opt,name=time_message,json=timeMessage,proto3" json:"time_message,omitempty"`
	Extra         []*FileInfo            `protobuf:"bytes,9,rep,name=extra,proto3" json:"extra,omitempty"`
	Avatar        string                 `protobuf:"bytes,10,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Reply         *BridgeMessageReply    `protobuf:"bytes,11,opt,name=reply,proto3" json:"reply,omitempty"`
	ReplyMap      map[string]string      `protobuf:"bytes,12,rep,name=reply_map,json=replyMap,proto3" json:"reply_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigId      string                 `protobuf:"bytes,13,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"` // UUIDv7 конфигурации реле
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToBridgeMessage) Reset() {
	*x = ToBridgeMessage{}
	mi := &file_bridge2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToBridgeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToBridgeMessage) ProtoMessage() {}

func (x *ToBridgeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bridge2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToBridgeMessage.ProtoReflect.Descriptor instead.
func (*ToBridgeMessage) Descriptor() ([]byte, []int) {
	return file_bridge2_proto_rawDescGZIP(), []int{2}
}

func (x *ToBridgeMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ToBridgeMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ToBridgeMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ToBridgeMessage) GetTip() string {
	if x != nil {
		return x.Tip
	}
	return ""
}

func (x *ToBridgeMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ToBridgeMessage) GetMesId() string {
	if x != nil {
		return x.MesId
	}
	return ""
}

func (x *ToBridgeMessage) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ToBridgeMessage) GetTimeMessage() int64 {
	if x != nil {
		return x.TimeMessage
	}
	return 0
}

func (x *ToBridgeMessage) GetExtra() []*FileInfo {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *ToBridgeMessage) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ToBridgeMessage) GetReply() *BridgeMessageReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *ToBridgeMessage) GetReplyMap() map[string]string {
	if x != nil {
		return x.ReplyMap
	}
	return nil
}

func (x *ToBridgeMessage) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

// Пустое сообщение для ответов, не требующих данных
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_bridge2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_bridge2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_bridge2_proto_rawDescGZIP(), []int{3}
}

var File_bridge2_proto protoreflect.FileDescriptor

const file_bridge2_proto_rawDesc = "" +
	"\n" +
	"\rbridge2.proto\x12\abridge2\"q\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x17\n" +
	"\afile_id\x18\x05 \x01(\tR\x06fileId\"\x80\x01\n" +
	"\x12BridgeMessageReply\x12!\n" +
	"\ftime_message\x18\x01 \x01(\x03R\vtimeMessage\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\"\xec\x03\n" +
	"\x0fToBridgeMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1a\n" +
	"\bsenderId\x18\x03 \x01(\tR\bsenderId\x12\x10\n" +
	"\x03tip\x18\x04 \x01(\tR\x03tip\x12\x17\n" +
	"\achat_id\x18\x05 \x01(\tR\x06chatId\x12\x15\n" +
	"\x06mes_id\x18\x06 \x01(\tR\x05mesId\x12\x19\n" +
	"\bguild_id\x18\a \x01(\tR\aguildId\x12!\n" +
	"\ftime_message\x18\b \x01(\x03R\vtimeMessage\x12'\n" +
	"\x05extra\x18\t \x03(\v2\x11.bridge2.FileInfoR\x05extra\x12\x16\n" +
	"\x06avatar\x18\n" +
	" \x01(\tR\x06avatar\x121\n" +
	"\x05reply\x18\v \x01(\v2\x1b.bridge2.BridgeMessageReplyR\x05reply\x12C\n" +
	"\treply_map\x18\f \x03(\v2&.bridge2.ToBridgeMessage.ReplyMapEntryR\breplyMap\x12\x1b\n" +
	"\tconfig_id\x18\r \x01(\tR\bconfigId\x1a;\n" +
	"\rReplyMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\a\n" +
	"\x05Empty2H\n" +
	"\rBridgeService\x127\n" +
	"\vInboxBridge\x12\x18.bridge2.ToBridgeMessage\x1a\x0e.bridge2.EmptyB/Z-github.com/mentalisit/restapi/bridge2;bridge2b\x06proto3"

var (
	file_bridge2_proto_rawDescOnce sync.Once
	file_bridge2_proto_rawDescData []byte
)

func file_bridge2_proto_rawDescGZIP() []byte {
	file_bridge2_proto_rawDescOnce.Do(func() {
		file_bridge2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge2_proto_rawDesc), len(file_bridge2_proto_rawDesc)))
	})
	return file_bridge2_proto_rawDescData
}

var file_bridge2_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bridge2_proto_goTypes = []any{
	(*FileInfo)(nil),           // 0: bridge2.FileInfo
	(*BridgeMessageReply)(nil), // 1: bridge2.BridgeMessageReply
	(*ToBridgeMessage)(nil),    // 2: bridge2.ToBridgeMessage
	(*Empty)(nil),              // 3: bridge2.Empty
	nil,                        // 4: bridge2.ToBridgeMessage.ReplyMapEntry
}
var file_bridge2_proto_depIdxs = []int32{
	0, // 0: bridge2.ToBridgeMessage.extra:type_name -> bridge2.FileInfo
	1, // 1: bridge2.ToBridgeMessage.reply:type_name -> bridge2.BridgeMessageReply
	4, // 2: bridge2.ToBridgeMessage.reply_map:type_name -> bridge2.ToBridgeMessage.ReplyMapEntry
	2, // 3: bridge2.BridgeService.InboxBridge:input_type -> bridge2.ToBridgeMessage
	3, // 4: bridge2.BridgeService.InboxBridge:output_type -> bridge2.Empty
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bridge2_proto_init() }
func file_bridge2_proto_init() {
	if File_bridge2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge2_proto_rawDesc), len(file_bridge2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge2_proto_goTypes,
		DependencyIndexes: file_bridge2_proto_depIdxs,
		MessageInfos:      file_bridge2_proto_msgTypes,
	}.Build()
	File_bridge2_proto = out.File
	file_bridge2_proto_goTypes = nil
	file_bridge2_proto_depIdxs = nil
}
